plugins {
  id 'java'
  id 'org.springframework.boot' version '4.1.1'
  id 'io.spring.dependency-management' version '1.1.7'
  id 'jvm-test-suite'
  id 'org.sonarqube' version '7.5.0.8588'
}

group = 'com.devops'
version = '0.0.1-SNAPSHOT'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-webmvc'
  implementation 'org.springframework.boot:spring-boot-starter-actuator'

  developmentOnly 'org.springframework.boot:spring-boot-devtools'
  developmentOnly 'org.springframework.boot:spring-boot-docker-compose'

  testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


sonar {
  properties {
    property "sonar.projectKey", "hoe-coder"
    property "sonar.organization", "FHVDevOps"
  }
}

testing {
  suites.configure {
    test {
      useJUnitJupiter()
    }

    register('integrationTest', JvmTestSuite) {
      useJUnitJupiter()

      dependencies {
        implementation project()
      }
    }
  }
}

tasks.named('test') {
  maxHeapSize = '1G'

  testLogging {
    events "passed", "skipped", "failed"
  }
}

