name: Build and Deploy Docs

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Ensure target directory exists
        run: mkdir -p src/main/resources/static/docs
      
      - name: Build MKDocs
        run: |
          docker run --rm \
            -u $(id -u):$(id -g) \
            -v "$PWD":/docs \
            squidfunk/mkdocs-material \
            build --clean --site-dir src/main/resources/static/docs

      - name: Build PDF
        run: |
          for f in docs/*.md; do
            if [ -f "$f" ]; then
              filename=$(basename -- "$f" .md)
              docker run --rm \
                -u $(id -u):$(id -g) \
                -v "$PWD":/data \
                pandoc/extra "$f" -o "src/main/resources/static/docs/${filename}.pdf"
            fi
          done
      
      - name: Build Docker
        run: |
          docker build -f Dockerfile -t app:latest .

      - name: Build Podman
        run: |
          podman build -f Containerfile -t localhost/app:latest .

      - name: Deploy Docker
        run: |
          docker rm -f devops-app 2>/dev/null || true

          docker run -d \
            --name devops-app \
            -p 8080:8080 \
            app:latest

      - name: Deploy Podman
        run: |
          export XDG_RUNTIME_DIR="/run/user/$(id -u)"
          export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
          
          mkdir -p ~/.config/containers/systemd/
          cp -av app.container ~/.config/containers/systemd/

          systemctl --user daemon-reload
          systemctl --user restart app.service
